import json
from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from db.session import Base

class Resource(Base):
    """
    Snapshots discovered infrastructure resources (K8s pods, nodes, or EC2 instances)
    with computed waste scores.
    """
    __tablename__ = "resources"

    id = Column(Integer, primary_key=True, autoincrement=True)
    resource_type = Column(String(50), nullable=False)  # 'pod', 'deployment', 'instance'
    resource_id = Column(String(255), nullable=False, index=True)
    namespace = Column(String(100), nullable=True)      # K8s namespace or AWS region
    current_cpu_request = Column(Float, default=0.0)    # Cores
    current_mem_request = Column(Float, default=0.0)    # Megabytes (MB)
    avg_cpu_usage = Column(Float, default=0.0)          # Actual measured CPU cores
    avg_mem_usage = Column(Float, default=0.0)          # Actual measured memory MB
    cost_per_hour = Column(Float, default=0.0)          # Hourly cost in INR
    waste_score = Column(Float, default=0.0)            # 0.0 - 100.0 (Higher = more waste)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "resource_type": self.resource_type,
            "resource_id": self.resource_id,
            "namespace": self.namespace,
            "current_cpu_request": self.current_cpu_request,
            "current_mem_request": self.current_mem_request,
            "avg_cpu_usage": self.avg_cpu_usage,
            "avg_mem_usage": self.avg_mem_usage,
            "cost_per_hour": self.cost_per_hour,
            "waste_score": round(self.waste_score, 1),
            "updated_at": self.updated_at.isoformat() if self.updated_at else None
        }

class OptimizationRun(Base):
    """
    Stores multi-agent optimization runs with before/after waste tracking and approval metrics.
    """
    __tablename__ = "optimization_runs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    triggered_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    mode = Column(String(20), default="dry_run", nullable=False)  # 'dry_run' | 'live'
    findings_count = Column(Integer, default=0)
    actions_count = Column(Integer, default=0)
    actions_approved = Column(Integer, default=0)
    actions_rejected = Column(Integer, default=0)
    savings_inr_month = Column(Float, default=0.0)
    before_waste_pct = Column(Float, default=0.0)       # e.g., 38.5%
    after_waste_pct = Column(Float, default=0.0)        # e.g., 12.0%
    slack_posted = Column(Boolean, default=False)
    summary_text = Column(Text, nullable=True)

    findings = relationship("Finding", back_populates="run", cascade="all, delete-orphan")

    def to_dict(self):
        return {
            "id": self.id,
            "triggered_at": self.triggered_at.isoformat() if self.triggered_at else None,
            "mode": self.mode,
            "findings_count": self.findings_count,
            "actions_count": self.actions_count,
            "actions_approved": self.actions_approved,
            "actions_rejected": self.actions_rejected,
            "savings_inr_month": round(self.savings_inr_month, 2),
            "before_waste_pct": round(self.before_waste_pct, 1),
            "after_waste_pct": round(self.after_waste_pct, 1),
            "slack_posted": self.slack_posted,
            "summary_text": self.summary_text
        }

class Finding(Base):
    """
    Granular optimization finding generated by Optimizer Agent, evaluated by Safety Agent,
    and executed by Executor Agent.
    """
    __tablename__ = "findings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(Integer, ForeignKey("optimization_runs.id"), nullable=False, index=True)
    resource_id = Column(String(255), nullable=False)
    resource_type = Column(String(50), nullable=False)   # 'pod', 'deployment', 'instance'
    issue_type = Column(String(50), nullable=False)      # 'idle', 'overprovisioned'
    utilization_pct = Column(Float, nullable=False)      # e.g., 2.5%
    proposed_action = Column(Text, nullable=False)       # JSON string of action parameters
    estimated_savings_inr_month = Column(Float, default=0.0)
    
    # What-If Simulation Fields
    predicted_util_pct = Column(Float, default=0.0)      # Simulated utilization post-action
    risk_score = Column(String(20), default="low")       # 'low', 'medium', 'high'
    risk_reason = Column(Text, nullable=True)            # Reasoning on SLO breach risk
    
    # Safety Governance Fields
    safety_decision = Column(String(30), default="auto_approve")  # 'auto_approve', 'require_approval', 'reject'
    safety_reason = Column(Text, nullable=True)                  # Natural language policy reasoning
    
    # Execution & Audit Trail
    executed = Column(Boolean, default=False)
    executed_at = Column(DateTime, nullable=True)
    approved_by = Column(String(50), default="system")           # 'system' or 'user'

    run = relationship("OptimizationRun", back_populates="findings")

    def get_action_json(self):
        try:
            return json.loads(self.proposed_action) if self.proposed_action else {}
        except Exception:
            return {"raw": self.proposed_action}

    def to_dict(self):
        return {
            "id": self.id,
            "run_id": self.run_id,
            "resource_id": self.resource_id,
            "resource_type": self.resource_type,
            "issue_type": self.issue_type,
            "utilization_pct": round(self.utilization_pct, 1),
            "proposed_action": self.get_action_json(),
            "estimated_savings_inr_month": round(self.estimated_savings_inr_month, 2),
            "predicted_util_pct": round(self.predicted_util_pct, 1),
            "risk_score": self.risk_score,
            "risk_reason": self.risk_reason,
            "safety_decision": self.safety_decision,
            "safety_reason": self.safety_reason,
            "executed": self.executed,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "approved_by": self.approved_by
        }
